# db server change
spring:
  profiles:
    active: local
    include: google


# server port setting
server:
  port: 8080
#  Api default url: /api
#  servlet.context-path: /api


spring.jackson.property-naming-strategy: SNAKE_CASE